# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/EnglishLearning/widgets/DialogTableDict_ui.py'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


