# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/EnglishLearning/widgets/DialogTableDict.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableDialogDict(object):
    def setupUi(self, TableDialogDict):
        TableDialogDict.setObjectName("TableDialogDict")
        TableDialogDict.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TableDialogDict)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table = QtWidgets.QTableWidget(parent=TableDialogDict)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table)
        self.add_btn = QtWidgets.QPushButton(parent=TableDialogDict)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_2.addWidget(self.add_btn)
        self.del_btn = QtWidgets.QPushButton(parent=TableDialogDict)
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout_2.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(TableDialogDict)
        QtCore.QMetaObject.connectSlotsByName(TableDialogDict)

    def retranslateUi(self, TableDialogDict):
        _translate = QtCore.QCoreApplication.translate
        TableDialogDict.setWindowTitle(_translate("TableDialogDict", "Dialog"))
        self.add_btn.setText(_translate("TableDialogDict", "add"))
        self.del_btn.setText(_translate("TableDialogDict", "del"))
