# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/EnglishLearning/widgets/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 466)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 291, 20))
        self.label.setObjectName("label")
        self.words_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.words_btn.setGeometry(QtCore.QRect(20, 100, 113, 32))
        self.words_btn.setObjectName("words_btn")
        self.train_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.train_btn.setGeometry(QtCore.QRect(180, 100, 113, 32))
        self.train_btn.setObjectName("train_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 407, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EnglishProject"))
        self.words_btn.setText(_translate("MainWindow", "Words"))
        self.train_btn.setText(_translate("MainWindow", "Training"))
