# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/EnglishLearning/widgets/windowTrain.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowTrain(object):
    def setupUi(self, WindowTrain):
        WindowTrain.setObjectName("WindowTrain")
        WindowTrain.resize(727, 456)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WindowTrain)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wordUp_lb = QtWidgets.QLabel(parent=WindowTrain)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.wordUp_lb.setFont(font)
        self.wordUp_lb.setStyleSheet("background-color: rgb(11, 11, 11);\n"
"color: rgb(223, 255, 0);")
        self.wordUp_lb.setText("")
        self.wordUp_lb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wordUp_lb.setObjectName("wordUp_lb")
        self.verticalLayout.addWidget(self.wordUp_lb)
        self.wordDown_lb = QtWidgets.QLabel(parent=WindowTrain)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.wordDown_lb.setFont(font)
        self.wordDown_lb.setStyleSheet("background-color: rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);")
        self.wordDown_lb.setText("")
        self.wordDown_lb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wordDown_lb.setObjectName("wordDown_lb")
        self.verticalLayout.addWidget(self.wordDown_lb)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WindowTrain)
        QtCore.QMetaObject.connectSlotsByName(WindowTrain)

    def retranslateUi(self, WindowTrain):
        _translate = QtCore.QCoreApplication.translate
        WindowTrain.setWindowTitle(_translate("WindowTrain", "Dialog"))
